region              = "us-west-2"
panorama_host       = "192.168.10.10"
auth-key            = "_AQ__ATK4JKrwhRYJdbZBKnSj2D9JeI"
dgname              = "AWS-GWLB-LAB"
tplname             = "stack-aws-gwlb-lab"
plugin-op-commands  = "panorama-licensing-mode-on"